<Block>
    size_hint:None,None
    size:(self.tile.width*self.scale,self.tile.height*2.125*self.scale) if self.tile is not None else (10,10)
    id:BLOCK
    bcol:1,1,1,1
    RelativeLayout:
        pos:(self.parent.animpos[0]+self.parent.animpos2[0],self.parent.animpos[1]+(self.height/4)+self.parent.animpos2[1])
        canvas.before:
            Color:
                rgba:BLOCK.bcol
            Rectangle:
                size:BLOCK.size
                source:BLOCK.sprite
